// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "AntFfi",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "AntFfi", targets: ["AntFfi"]),
    ],
    targets: [
        // Native Rust library packaged as an .xcframework with slices for
        // iOS device, iOS simulator (arm64), and macOS arm64.
        // URL + checksum are rewritten by ant-sdk's release CI on every tag.
        .binaryTarget(
            name: "ant_ffiFFI",
            url: "https://github.com/WithAutonomi/ant-swift/releases/download/v0.0.1/AntFfi.xcframework.zip",
            checksum: "e257d885977a2b34318bd1a0f0fc5aa1e48c3606dd20fd5f816749f375106295"
        ),
        // Swift glue auto-generated by uniffi-bindgen.
        .target(
            name: "AntFfi",
            dependencies: ["ant_ffiFFI"],
            path: "Sources/AntFfi"
        ),
    ]
)
