// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "AntFfi",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(name: "AntFfi", targets: ["AntFfi"]),
    ],
    targets: [
        // Native Rust library packaged as an .xcframework with slices for
        // iOS device, iOS simulator (arm64), and macOS arm64.
        // URL + checksum are rewritten by ant-sdk's release CI on every tag.
        .binaryTarget(
            name: "ant_ffiFFI",
            url: "https://github.com/WithAutonomi/ant-swift/releases/download/v0.0.2/AntFfi.xcframework.zip",
            checksum: "012cf25dc914ba76518bd2125249d401d25df2660a5448d3dc1c48a417491f71"
        ),
        // Swift glue auto-generated by uniffi-bindgen.
        // The linkedFramework entries are required by symbols inside the
        // static .a (hyper_util's proxy detection, rustls/security_framework
        // TLS, etc.) — static libs don't auto-convey framework dependencies
        // through the xcframework, so consumers would otherwise see undefined
        // symbol errors at link time.
        .target(
            name: "AntFfi",
            dependencies: ["ant_ffiFFI"],
            path: "Sources/AntFfi",
            linkerSettings: [
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
                .linkedLibrary("c++"),
            ]
        ),
    ]
)
