// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ant_ffiFFI)
import ant_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ant_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ant_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureAntFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Autonomi network client (wraps ant-core Client).
 *
 * Provides direct access to the Autonomi network without needing
 * an antd daemon. Suitable for mobile apps (Android/iOS).
 */
public protocol ClientProtocol: AnyObject, Sendable {
    
    /**
     * Check if a chunk exists on the network.
     */
    func chunkExists(addressHex: String) async throws  -> Bool
    
    /**
     * Retrieve a chunk by hex-encoded address.
     */
    func chunkGet(addressHex: String) async throws  -> Data
    
    /**
     * Store a chunk on the network.
     */
    func chunkPut(data: Data) async throws  -> ChunkPutResult
    
    /**
     * Retrieve private data using a hex-encoded data map.
     */
    func dataGetPrivate(dataMapHex: String) async throws  -> Data
    
    /**
     * Retrieve public data by hex-encoded address.
     */
    func dataGetPublic(addressHex: String) async throws  -> Data
    
    /**
     * Upload private data. Returns the serialized data map (hex).
     */
    func dataPutPrivate(data: Data, paymentMode: String) async throws  -> DataPutPrivateResult
    
    /**
     * Upload public data. Returns the address of the stored data map.
     */
    func dataPutPublic(data: Data, paymentMode: String) async throws  -> DataPutPublicResult
    
    /**
     * Download private data by hex-encoded data map straight to a file on
     * disk, reporting live progress. Returns bytes written.
     */
    func downloadPrivateToFile(dataMapHex: String, destPath: String, listener: ProgressListener) async throws  -> UInt64
    
    /**
     * Download public data by address straight to a file on disk, reporting
     * live progress (`"resolving"` then `"downloading"` phases). Returns bytes
     * written.
     */
    func downloadPublicToFile(addressHex: String, destPath: String, listener: ProgressListener) async throws  -> UInt64
    
    /**
     * Download a file to disk by hex-encoded address.
     */
    func fileDownloadPublic(addressHex: String, destPath: String) async throws 
    
    /**
     * Upload a file from disk (public). Returns the address.
     */
    func fileUploadPublic(path: String, paymentMode: String) async throws  -> FilePutPublicResult
    
    /**
     * Phase 2 (external signer): after the external wallet has paid
     * (`payForQuotes`), finalize the upload by supplying the resulting
     * `quote_hash -> tx_hash` map (both 0x-prefixed hex). Stores the chunks
     * and returns the data map / address. `upload_id` comes from a prior
     * `prepare_*` call. If everything was already stored, pass an empty map.
     */
    func finalizeUpload(uploadId: String, txHashes: [String: String]) async throws  -> ExternalUploadResult
    
    /**
     * Same as [`Self::finalize_upload`] but reports live storing progress:
     * `listener` gets `"storing"` updates (`done`/`total` chunks) as chunks
     * land on the network.
     */
    func finalizeUploadWithProgress(uploadId: String, txHashes: [String: String], listener: ProgressListener) async throws  -> ExternalUploadResult
    
    /**
     * Phase 1 (external signer): encrypt `data`, collect quotes, and return
     * the payment summary. `visibility` is `"public"` or `"private"`. The
     * prepared state is retained under the returned `upload_id` until
     * [`Self::finalize_upload`].
     */
    func prepareDataUpload(data: Data, visibility: String) async throws  -> PreparedUploadInfo
    
    /**
     * Phase 1 (external signer): same as [`Self::prepare_data_upload`] but for
     * a file on disk.
     */
    func prepareFileUpload(path: String, visibility: String) async throws  -> PreparedUploadInfo
    
    /**
     * Approve token spend for storage payments (one-time).
     */
    func walletApprove() async throws 
    
}
/**
 * Autonomi network client (wraps ant-core Client).
 *
 * Provides direct access to the Autonomi network without needing
 * an antd daemon. Suitable for mobile apps (Android/iOS).
 */
open class Client: ClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ant_ffi_fn_clone_client(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ant_ffi_fn_free_client(pointer, $0) }
    }

    
    /**
     * Connect to the network using explicit bootstrap peers.
     */
public static func connect(peers: [String])async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_constructor_client_connect(FfiConverterSequenceString.lower(peers)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_ant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_ant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Connect with an EVM network configured but **no wallet / private key**.
     *
     * This is the external-signer entry point: quote collection and price
     * queries work (they need the network), but payment is signed off-device
     * by an external wallet (e.g. WalletConnect). Use [`Self::prepare_data_upload`]
     * / [`Self::prepare_file_upload`] then [`Self::finalize_upload`].
     */
public static func connectForExternalSigner(peers: [String], rpcUrl: String, paymentTokenAddress: String, paymentVaultAddress: String)async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_constructor_client_connect_for_external_signer(FfiConverterSequenceString.lower(peers),FfiConverterString.lower(rpcUrl),FfiConverterString.lower(paymentTokenAddress),FfiConverterString.lower(paymentVaultAddress)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_ant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_ant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Connect to a locally running devnet using the manifest JSON file the
     * devnet wrote on startup (`LocalDevnet::write_manifest`).
     *
     * Reads bootstrap peers, EVM RPC URL + contract addresses, and the
     * funded wallet private key from the manifest, then constructs a Client
     * with the wallet attached. Suitable for **development and testing
     * only** — production code should provide bootstrap peers and wallet
     * material explicitly via [`Self::connect_with_wallet`].
     *
     * Fails if the manifest doesn't exist, is malformed, or has no `evm`
     * section (a devnet started without payment enforcement).
     */
public static func connectFromDevnetManifest(path: String)async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_constructor_client_connect_from_devnet_manifest(FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_ant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_ant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Like [`Self::connect_from_devnet_manifest`] but for the **external-signer**
     * flow: configures the devnet's EVM network for quote/price queries but
     * attaches **no wallet** (the manifest's `wallet_private_key` may be empty
     * — e.g. the Sepolia devnet, which expects you to bring your own wallet).
     * Pay via `prepare_*` + an external signer + `finalize_upload`.
     */
public static func connectFromDevnetManifestExternalSigner(path: String)async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_constructor_client_connect_from_devnet_manifest_external_signer(FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_ant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_ant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Connect to a local test network.
     */
public static func connectLocal()async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_constructor_client_connect_local(
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_ant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_ant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Connect to the network with a wallet configured for write operations.
     *
     * Takes the wallet private key and EVM network details directly,
     * since the wallet must be constructed fresh for ownership transfer.
     */
public static func connectWithWallet(peers: [String], privateKey: String, rpcUrl: String, paymentTokenAddress: String, paymentVaultAddress: String)async throws  -> Client  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_constructor_client_connect_with_wallet(FfiConverterSequenceString.lower(peers),FfiConverterString.lower(privateKey),FfiConverterString.lower(rpcUrl),FfiConverterString.lower(paymentTokenAddress),FfiConverterString.lower(paymentVaultAddress)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_pointer,
            completeFunc: ffi_ant_ffi_rust_future_complete_pointer,
            freeFunc: ffi_ant_ffi_rust_future_free_pointer,
            liftFunc: FfiConverterTypeClient_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    

    
    /**
     * Check if a chunk exists on the network.
     */
open func chunkExists(addressHex: String)async throws  -> Bool  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_chunk_exists(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(addressHex)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_i8,
            completeFunc: ffi_ant_ffi_rust_future_complete_i8,
            freeFunc: ffi_ant_ffi_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Retrieve a chunk by hex-encoded address.
     */
open func chunkGet(addressHex: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_chunk_get(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(addressHex)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Store a chunk on the network.
     */
open func chunkPut(data: Data)async throws  -> ChunkPutResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_chunk_put(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeChunkPutResult_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Retrieve private data using a hex-encoded data map.
     */
open func dataGetPrivate(dataMapHex: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_data_get_private(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(dataMapHex)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Retrieve public data by hex-encoded address.
     */
open func dataGetPublic(addressHex: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_data_get_public(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(addressHex)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Upload private data. Returns the serialized data map (hex).
     */
open func dataPutPrivate(data: Data, paymentMode: String)async throws  -> DataPutPrivateResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_data_put_private(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data),FfiConverterString.lower(paymentMode)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeDataPutPrivateResult_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Upload public data. Returns the address of the stored data map.
     */
open func dataPutPublic(data: Data, paymentMode: String)async throws  -> DataPutPublicResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_data_put_public(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data),FfiConverterString.lower(paymentMode)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeDataPutPublicResult_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Download private data by hex-encoded data map straight to a file on
     * disk, reporting live progress. Returns bytes written.
     */
open func downloadPrivateToFile(dataMapHex: String, destPath: String, listener: ProgressListener)async throws  -> UInt64  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_download_private_to_file(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(dataMapHex),FfiConverterString.lower(destPath),FfiConverterCallbackInterfaceProgressListener_lower(listener)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_u64,
            completeFunc: ffi_ant_ffi_rust_future_complete_u64,
            freeFunc: ffi_ant_ffi_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Download public data by address straight to a file on disk, reporting
     * live progress (`"resolving"` then `"downloading"` phases). Returns bytes
     * written.
     */
open func downloadPublicToFile(addressHex: String, destPath: String, listener: ProgressListener)async throws  -> UInt64  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_download_public_to_file(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(addressHex),FfiConverterString.lower(destPath),FfiConverterCallbackInterfaceProgressListener_lower(listener)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_u64,
            completeFunc: ffi_ant_ffi_rust_future_complete_u64,
            freeFunc: ffi_ant_ffi_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Download a file to disk by hex-encoded address.
     */
open func fileDownloadPublic(addressHex: String, destPath: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_file_download_public(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(addressHex),FfiConverterString.lower(destPath)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_void,
            completeFunc: ffi_ant_ffi_rust_future_complete_void,
            freeFunc: ffi_ant_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Upload a file from disk (public). Returns the address.
     */
open func fileUploadPublic(path: String, paymentMode: String)async throws  -> FilePutPublicResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_file_upload_public(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(path),FfiConverterString.lower(paymentMode)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFilePutPublicResult_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Phase 2 (external signer): after the external wallet has paid
     * (`payForQuotes`), finalize the upload by supplying the resulting
     * `quote_hash -> tx_hash` map (both 0x-prefixed hex). Stores the chunks
     * and returns the data map / address. `upload_id` comes from a prior
     * `prepare_*` call. If everything was already stored, pass an empty map.
     */
open func finalizeUpload(uploadId: String, txHashes: [String: String])async throws  -> ExternalUploadResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_finalize_upload(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(uploadId),FfiConverterDictionaryStringString.lower(txHashes)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeExternalUploadResult_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Same as [`Self::finalize_upload`] but reports live storing progress:
     * `listener` gets `"storing"` updates (`done`/`total` chunks) as chunks
     * land on the network.
     */
open func finalizeUploadWithProgress(uploadId: String, txHashes: [String: String], listener: ProgressListener)async throws  -> ExternalUploadResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_finalize_upload_with_progress(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(uploadId),FfiConverterDictionaryStringString.lower(txHashes),FfiConverterCallbackInterfaceProgressListener_lower(listener)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeExternalUploadResult_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Phase 1 (external signer): encrypt `data`, collect quotes, and return
     * the payment summary. `visibility` is `"public"` or `"private"`. The
     * prepared state is retained under the returned `upload_id` until
     * [`Self::finalize_upload`].
     */
open func prepareDataUpload(data: Data, visibility: String)async throws  -> PreparedUploadInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_prepare_data_upload(
                    self.uniffiClonePointer(),
                    FfiConverterData.lower(data),FfiConverterString.lower(visibility)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypePreparedUploadInfo_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Phase 1 (external signer): same as [`Self::prepare_data_upload`] but for
     * a file on disk.
     */
open func prepareFileUpload(path: String, visibility: String)async throws  -> PreparedUploadInfo  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_prepare_file_upload(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(path),FfiConverterString.lower(visibility)
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypePreparedUploadInfo_lift,
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    
    /**
     * Approve token spend for storage payments (one-time).
     */
open func walletApprove()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_client_wallet_approve(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_void,
            completeFunc: ffi_ant_ffi_rust_future_complete_void,
            freeFunc: ffi_ant_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeClientError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Client

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Client {
        return Client(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Client) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Client {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Client, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> Client {
    return try FfiConverterTypeClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClient_lower(_ value: Client) -> UnsafeMutableRawPointer {
    return FfiConverterTypeClient.lower(value)
}






/**
 * EVM wallet for paying storage costs.
 */
public protocol WalletProtocol: AnyObject, Sendable {
    
    /**
     * Get the wallet's public address (hex with 0x prefix).
     */
    func address()  -> String
    
    /**
     * Get the wallet's gas token balance (wei as decimal string).
     */
    func balanceOfGasTokens() async throws  -> String
    
    /**
     * Get the wallet's token balance (atto tokens as decimal string).
     */
    func balanceOfTokens() async throws  -> String
    
}
/**
 * EVM wallet for paying storage costs.
 */
open class Wallet: WalletProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_ant_ffi_fn_clone_wallet(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_ant_ffi_fn_free_wallet(pointer, $0) }
    }

    
    /**
     * Create a wallet from an EVM private key.
     *
     * Uses the default Autonomi EVM network configuration.
     */
public static func fromPrivateKey(privateKey: String, rpcUrl: String, paymentTokenAddress: String, paymentVaultAddress: String)throws  -> Wallet  {
    return try  FfiConverterTypeWallet_lift(try rustCallWithError(FfiConverterTypeWalletError_lift) {
    uniffi_ant_ffi_fn_constructor_wallet_from_private_key(
        FfiConverterString.lower(privateKey),
        FfiConverterString.lower(rpcUrl),
        FfiConverterString.lower(paymentTokenAddress),
        FfiConverterString.lower(paymentVaultAddress),$0
    )
})
}
    

    
    /**
     * Get the wallet's public address (hex with 0x prefix).
     */
open func address() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_ant_ffi_fn_method_wallet_address(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the wallet's gas token balance (wei as decimal string).
     */
open func balanceOfGasTokens()async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_wallet_balance_of_gas_tokens(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeWalletError_lift
        )
}
    
    /**
     * Get the wallet's token balance (atto tokens as decimal string).
     */
open func balanceOfTokens()async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ant_ffi_fn_method_wallet_balance_of_tokens(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_ant_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_ant_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_ant_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeWalletError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWallet: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Wallet

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Wallet {
        return Wallet(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Wallet) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Wallet {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Wallet, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lift(_ pointer: UnsafeMutableRawPointer) throws -> Wallet {
    return try FfiConverterTypeWallet.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lower(_ value: Wallet) -> UnsafeMutableRawPointer {
    return FfiConverterTypeWallet.lower(value)
}




/**
 * Result of storing a chunk on the network.
 */
public struct ChunkPutResult {
    /**
     * Hex-encoded chunk address (32 bytes).
     */
    public var address: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded chunk address (32 bytes).
         */address: String) {
        self.address = address
    }
}

#if compiler(>=6)
extension ChunkPutResult: Sendable {}
#endif


extension ChunkPutResult: Equatable, Hashable {
    public static func ==(lhs: ChunkPutResult, rhs: ChunkPutResult) -> Bool {
        if lhs.address != rhs.address {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChunkPutResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChunkPutResult {
        return
            try ChunkPutResult(
                address: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ChunkPutResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChunkPutResult_lift(_ buf: RustBuffer) throws -> ChunkPutResult {
    return try FfiConverterTypeChunkPutResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChunkPutResult_lower(_ value: ChunkPutResult) -> RustBuffer {
    return FfiConverterTypeChunkPutResult.lower(value)
}


/**
 * Result of a private data upload (data map returned to caller).
 */
public struct DataPutPrivateResult {
    /**
     * Hex-encoded serialized data map (caller keeps this secret).
     */
    public var dataMap: String
    /**
     * Number of chunks stored.
     */
    public var chunksStored: UInt64
    /**
     * Payment mode that was used.
     */
    public var paymentModeUsed: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded serialized data map (caller keeps this secret).
         */dataMap: String, 
        /**
         * Number of chunks stored.
         */chunksStored: UInt64, 
        /**
         * Payment mode that was used.
         */paymentModeUsed: String) {
        self.dataMap = dataMap
        self.chunksStored = chunksStored
        self.paymentModeUsed = paymentModeUsed
    }
}

#if compiler(>=6)
extension DataPutPrivateResult: Sendable {}
#endif


extension DataPutPrivateResult: Equatable, Hashable {
    public static func ==(lhs: DataPutPrivateResult, rhs: DataPutPrivateResult) -> Bool {
        if lhs.dataMap != rhs.dataMap {
            return false
        }
        if lhs.chunksStored != rhs.chunksStored {
            return false
        }
        if lhs.paymentModeUsed != rhs.paymentModeUsed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dataMap)
        hasher.combine(chunksStored)
        hasher.combine(paymentModeUsed)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataPutPrivateResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataPutPrivateResult {
        return
            try DataPutPrivateResult(
                dataMap: FfiConverterString.read(from: &buf), 
                chunksStored: FfiConverterUInt64.read(from: &buf), 
                paymentModeUsed: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DataPutPrivateResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dataMap, into: &buf)
        FfiConverterUInt64.write(value.chunksStored, into: &buf)
        FfiConverterString.write(value.paymentModeUsed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataPutPrivateResult_lift(_ buf: RustBuffer) throws -> DataPutPrivateResult {
    return try FfiConverterTypeDataPutPrivateResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataPutPrivateResult_lower(_ value: DataPutPrivateResult) -> RustBuffer {
    return FfiConverterTypeDataPutPrivateResult.lower(value)
}


/**
 * Result of a public data upload (data map stored as public chunk).
 */
public struct DataPutPublicResult {
    /**
     * Hex-encoded address of the stored data map.
     */
    public var address: String
    /**
     * Number of chunks stored.
     */
    public var chunksStored: UInt64
    /**
     * Payment mode that was used: "auto", "merkle", or "single".
     */
    public var paymentModeUsed: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded address of the stored data map.
         */address: String, 
        /**
         * Number of chunks stored.
         */chunksStored: UInt64, 
        /**
         * Payment mode that was used: "auto", "merkle", or "single".
         */paymentModeUsed: String) {
        self.address = address
        self.chunksStored = chunksStored
        self.paymentModeUsed = paymentModeUsed
    }
}

#if compiler(>=6)
extension DataPutPublicResult: Sendable {}
#endif


extension DataPutPublicResult: Equatable, Hashable {
    public static func ==(lhs: DataPutPublicResult, rhs: DataPutPublicResult) -> Bool {
        if lhs.address != rhs.address {
            return false
        }
        if lhs.chunksStored != rhs.chunksStored {
            return false
        }
        if lhs.paymentModeUsed != rhs.paymentModeUsed {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address)
        hasher.combine(chunksStored)
        hasher.combine(paymentModeUsed)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataPutPublicResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataPutPublicResult {
        return
            try DataPutPublicResult(
                address: FfiConverterString.read(from: &buf), 
                chunksStored: FfiConverterUInt64.read(from: &buf), 
                paymentModeUsed: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DataPutPublicResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterUInt64.write(value.chunksStored, into: &buf)
        FfiConverterString.write(value.paymentModeUsed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataPutPublicResult_lift(_ buf: RustBuffer) throws -> DataPutPublicResult {
    return try FfiConverterTypeDataPutPublicResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDataPutPublicResult_lower(_ value: DataPutPublicResult) -> RustBuffer {
    return FfiConverterTypeDataPutPublicResult.lower(value)
}


/**
 * Result of finalizing an external-signer upload.
 */
public struct ExternalUploadResult {
    /**
     * Hex-encoded serialized data map (for private retrieval; always present).
     */
    public var dataMap: String
    /**
     * For public uploads: hex data-map address (shareable). `None` if private.
     */
    public var address: String?
    /**
     * Number of chunks stored on the network.
     */
    public var chunksStored: UInt64
    /**
     * Total storage cost paid, in atto-tokens (base-10). "0" if all pre-existed.
     */
    public var storageCostAtto: String
    /**
     * Total gas cost in wei (base-10).
     */
    public var gasCostWei: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded serialized data map (for private retrieval; always present).
         */dataMap: String, 
        /**
         * For public uploads: hex data-map address (shareable). `None` if private.
         */address: String?, 
        /**
         * Number of chunks stored on the network.
         */chunksStored: UInt64, 
        /**
         * Total storage cost paid, in atto-tokens (base-10). "0" if all pre-existed.
         */storageCostAtto: String, 
        /**
         * Total gas cost in wei (base-10).
         */gasCostWei: String) {
        self.dataMap = dataMap
        self.address = address
        self.chunksStored = chunksStored
        self.storageCostAtto = storageCostAtto
        self.gasCostWei = gasCostWei
    }
}

#if compiler(>=6)
extension ExternalUploadResult: Sendable {}
#endif


extension ExternalUploadResult: Equatable, Hashable {
    public static func ==(lhs: ExternalUploadResult, rhs: ExternalUploadResult) -> Bool {
        if lhs.dataMap != rhs.dataMap {
            return false
        }
        if lhs.address != rhs.address {
            return false
        }
        if lhs.chunksStored != rhs.chunksStored {
            return false
        }
        if lhs.storageCostAtto != rhs.storageCostAtto {
            return false
        }
        if lhs.gasCostWei != rhs.gasCostWei {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dataMap)
        hasher.combine(address)
        hasher.combine(chunksStored)
        hasher.combine(storageCostAtto)
        hasher.combine(gasCostWei)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeExternalUploadResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ExternalUploadResult {
        return
            try ExternalUploadResult(
                dataMap: FfiConverterString.read(from: &buf), 
                address: FfiConverterOptionString.read(from: &buf), 
                chunksStored: FfiConverterUInt64.read(from: &buf), 
                storageCostAtto: FfiConverterString.read(from: &buf), 
                gasCostWei: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ExternalUploadResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dataMap, into: &buf)
        FfiConverterOptionString.write(value.address, into: &buf)
        FfiConverterUInt64.write(value.chunksStored, into: &buf)
        FfiConverterString.write(value.storageCostAtto, into: &buf)
        FfiConverterString.write(value.gasCostWei, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExternalUploadResult_lift(_ buf: RustBuffer) throws -> ExternalUploadResult {
    return try FfiConverterTypeExternalUploadResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeExternalUploadResult_lower(_ value: ExternalUploadResult) -> RustBuffer {
    return FfiConverterTypeExternalUploadResult.lower(value)
}


/**
 * Result of uploading a file (public).
 */
public struct FilePutPublicResult {
    /**
     * Hex-encoded address of the stored data map.
     */
    public var address: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Hex-encoded address of the stored data map.
         */address: String) {
        self.address = address
    }
}

#if compiler(>=6)
extension FilePutPublicResult: Sendable {}
#endif


extension FilePutPublicResult: Equatable, Hashable {
    public static func ==(lhs: FilePutPublicResult, rhs: FilePutPublicResult) -> Bool {
        if lhs.address != rhs.address {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(address)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFilePutPublicResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FilePutPublicResult {
        return
            try FilePutPublicResult(
                address: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FilePutPublicResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilePutPublicResult_lift(_ buf: RustBuffer) throws -> FilePutPublicResult {
    return try FfiConverterTypeFilePutPublicResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilePutPublicResult_lower(_ value: FilePutPublicResult) -> RustBuffer {
    return FfiConverterTypeFilePutPublicResult.lower(value)
}


/**
 * A single on-chain payment the external wallet must settle: one entry of the
 * `payForQuotes((address,uint256,bytes32)[])` call.
 */
public struct PaymentEntry {
    /**
     * 0x-prefixed quote hash (32 bytes) — the key in the tx-hash map at finalize.
     */
    public var quoteHash: String
    /**
     * 0x-prefixed EVM rewards address to pay.
     */
    public var rewardsAddress: String
    /**
     * Amount to pay in atto-tokens (base-10 string; exceeds u64).
     */
    public var amount: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 0x-prefixed quote hash (32 bytes) — the key in the tx-hash map at finalize.
         */quoteHash: String, 
        /**
         * 0x-prefixed EVM rewards address to pay.
         */rewardsAddress: String, 
        /**
         * Amount to pay in atto-tokens (base-10 string; exceeds u64).
         */amount: String) {
        self.quoteHash = quoteHash
        self.rewardsAddress = rewardsAddress
        self.amount = amount
    }
}

#if compiler(>=6)
extension PaymentEntry: Sendable {}
#endif


extension PaymentEntry: Equatable, Hashable {
    public static func ==(lhs: PaymentEntry, rhs: PaymentEntry) -> Bool {
        if lhs.quoteHash != rhs.quoteHash {
            return false
        }
        if lhs.rewardsAddress != rhs.rewardsAddress {
            return false
        }
        if lhs.amount != rhs.amount {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(quoteHash)
        hasher.combine(rewardsAddress)
        hasher.combine(amount)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePaymentEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PaymentEntry {
        return
            try PaymentEntry(
                quoteHash: FfiConverterString.read(from: &buf), 
                rewardsAddress: FfiConverterString.read(from: &buf), 
                amount: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: PaymentEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.quoteHash, into: &buf)
        FfiConverterString.write(value.rewardsAddress, into: &buf)
        FfiConverterString.write(value.amount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaymentEntry_lift(_ buf: RustBuffer) throws -> PaymentEntry {
    return try FfiConverterTypePaymentEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePaymentEntry_lower(_ value: PaymentEntry) -> RustBuffer {
    return FfiConverterTypePaymentEntry.lower(value)
}


/**
 * Summary of a prepared external-signer upload. The heavy prepared-chunk
 * state stays in Rust, referenced by `upload_id` until `finalize_upload`.
 * The caller uses `payments` to build ERC-20 `approve` + `payForQuotes`,
 * has the external wallet sign them, then calls `finalize_upload` with the
 * resulting `quote_hash -> tx_hash` map.
 */
public struct PreparedUploadInfo {
    /**
     * Opaque handle for this prepared upload; pass to `finalize_upload`.
     */
    public var uploadId: String
    /**
     * Payment shape. Currently always `"wave_batch"` (merkle not yet exposed).
     */
    public var paymentType: String
    /**
     * Per-quote payments to settle on-chain. Empty if everything was already stored.
     */
    public var payments: [PaymentEntry]
    /**
     * Total across all payments (atto-tokens, base-10).
     */
    public var totalAmount: String
    /**
     * For public uploads: hex address the data is retrievable from after
     * finalize. `None` for private uploads.
     */
    public var dataMapAddress: String?
    /**
     * True if every chunk already existed on the network — `payments` is
     * empty and `finalize_upload` may be called with an empty map.
     */
    public var alreadyStored: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Opaque handle for this prepared upload; pass to `finalize_upload`.
         */uploadId: String, 
        /**
         * Payment shape. Currently always `"wave_batch"` (merkle not yet exposed).
         */paymentType: String, 
        /**
         * Per-quote payments to settle on-chain. Empty if everything was already stored.
         */payments: [PaymentEntry], 
        /**
         * Total across all payments (atto-tokens, base-10).
         */totalAmount: String, 
        /**
         * For public uploads: hex address the data is retrievable from after
         * finalize. `None` for private uploads.
         */dataMapAddress: String?, 
        /**
         * True if every chunk already existed on the network — `payments` is
         * empty and `finalize_upload` may be called with an empty map.
         */alreadyStored: Bool) {
        self.uploadId = uploadId
        self.paymentType = paymentType
        self.payments = payments
        self.totalAmount = totalAmount
        self.dataMapAddress = dataMapAddress
        self.alreadyStored = alreadyStored
    }
}

#if compiler(>=6)
extension PreparedUploadInfo: Sendable {}
#endif


extension PreparedUploadInfo: Equatable, Hashable {
    public static func ==(lhs: PreparedUploadInfo, rhs: PreparedUploadInfo) -> Bool {
        if lhs.uploadId != rhs.uploadId {
            return false
        }
        if lhs.paymentType != rhs.paymentType {
            return false
        }
        if lhs.payments != rhs.payments {
            return false
        }
        if lhs.totalAmount != rhs.totalAmount {
            return false
        }
        if lhs.dataMapAddress != rhs.dataMapAddress {
            return false
        }
        if lhs.alreadyStored != rhs.alreadyStored {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(uploadId)
        hasher.combine(paymentType)
        hasher.combine(payments)
        hasher.combine(totalAmount)
        hasher.combine(dataMapAddress)
        hasher.combine(alreadyStored)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePreparedUploadInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PreparedUploadInfo {
        return
            try PreparedUploadInfo(
                uploadId: FfiConverterString.read(from: &buf), 
                paymentType: FfiConverterString.read(from: &buf), 
                payments: FfiConverterSequenceTypePaymentEntry.read(from: &buf), 
                totalAmount: FfiConverterString.read(from: &buf), 
                dataMapAddress: FfiConverterOptionString.read(from: &buf), 
                alreadyStored: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: PreparedUploadInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uploadId, into: &buf)
        FfiConverterString.write(value.paymentType, into: &buf)
        FfiConverterSequenceTypePaymentEntry.write(value.payments, into: &buf)
        FfiConverterString.write(value.totalAmount, into: &buf)
        FfiConverterOptionString.write(value.dataMapAddress, into: &buf)
        FfiConverterBool.write(value.alreadyStored, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedUploadInfo_lift(_ buf: RustBuffer) throws -> PreparedUploadInfo {
    return try FfiConverterTypePreparedUploadInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePreparedUploadInfo_lower(_ value: PreparedUploadInfo) -> RustBuffer {
    return FfiConverterTypePreparedUploadInfo.lower(value)
}


/**
 * A progress update for a long-running upload or download, delivered to a
 * [`ProgressListener`]. `phase` is one of:
 * - upload:   `"encrypting"`, `"quoting"`, `"storing"`
 * - download: `"resolving"`, `"downloading"`
 * `total` is 0 when the total isn't known yet (show an indeterminate bar);
 * otherwise `done / total` is a 0..1 fraction of the current phase.
 */
public struct ProgressUpdate {
    public var phase: String
    public var done: UInt64
    public var total: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(phase: String, done: UInt64, total: UInt64) {
        self.phase = phase
        self.done = done
        self.total = total
    }
}

#if compiler(>=6)
extension ProgressUpdate: Sendable {}
#endif


extension ProgressUpdate: Equatable, Hashable {
    public static func ==(lhs: ProgressUpdate, rhs: ProgressUpdate) -> Bool {
        if lhs.phase != rhs.phase {
            return false
        }
        if lhs.done != rhs.done {
            return false
        }
        if lhs.total != rhs.total {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(phase)
        hasher.combine(done)
        hasher.combine(total)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProgressUpdate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProgressUpdate {
        return
            try ProgressUpdate(
                phase: FfiConverterString.read(from: &buf), 
                done: FfiConverterUInt64.read(from: &buf), 
                total: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ProgressUpdate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.phase, into: &buf)
        FfiConverterUInt64.write(value.done, into: &buf)
        FfiConverterUInt64.write(value.total, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProgressUpdate_lift(_ buf: RustBuffer) throws -> ProgressUpdate {
    return try FfiConverterTypeProgressUpdate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProgressUpdate_lower(_ value: ProgressUpdate) -> RustBuffer {
    return FfiConverterTypeProgressUpdate.lower(value)
}


/**
 * Error type for client operations.
 */
public enum ClientError: Swift.Error {

    
    
    case InitializationFailed(reason: String
    )
    case NetworkError(reason: String
    )
    case PaymentError(reason: String
    )
    case InvalidInput(reason: String
    )
    case NotFound(reason: String
    )
    case AlreadyExists
    case WalletNotConfigured
    case InternalError(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientError: FfiConverterRustBuffer {
    typealias SwiftType = ClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitializationFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NetworkError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .PaymentError(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidInput(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .NotFound(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 6: return .AlreadyExists
        case 7: return .WalletNotConfigured
        case 8: return .InternalError(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InitializationFailed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .NetworkError(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .PaymentError(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .InvalidInput(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .NotFound(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .AlreadyExists:
            writeInt(&buf, Int32(6))
        
        
        case .WalletNotConfigured:
            writeInt(&buf, Int32(7))
        
        
        case let .InternalError(reason):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientError_lift(_ buf: RustBuffer) throws -> ClientError {
    return try FfiConverterTypeClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientError_lower(_ value: ClientError) -> RustBuffer {
    return FfiConverterTypeClientError.lower(value)
}


extension ClientError: Equatable, Hashable {}




extension ClientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}





/**
 * Error type for wallet operations.
 */
public enum WalletError: Swift.Error {

    
    
    case CreationFailed(reason: String
    )
    case OperationFailed(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletError: FfiConverterRustBuffer {
    typealias SwiftType = WalletError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .CreationFailed(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 2: return .OperationFailed(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WalletError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .CreationFailed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .OperationFailed(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletError_lift(_ buf: RustBuffer) throws -> WalletError {
    return try FfiConverterTypeWalletError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletError_lower(_ value: WalletError) -> RustBuffer {
    return FfiConverterTypeWalletError.lower(value)
}


extension WalletError: Equatable, Hashable {}




extension WalletError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}







/**
 * Foreign callback invoked as an upload/download progresses. Implement it on
 * the Swift/Kotlin side and pass it to the `*_with_progress` client methods.
 * Calls arrive on a background thread — marshal to the UI thread before
 * touching UI state.
 */
public protocol ProgressListener: AnyObject, Sendable {
    
    func onProgress(update: ProgressUpdate) 
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceProgressListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceProgressListener] = [UniffiVTableCallbackInterfaceProgressListener(
        onProgress: { (
            uniffiHandle: UInt64,
            update: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     update: try FfiConverterTypeProgressUpdate_lift(update)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfaceProgressListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface ProgressListener: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitProgressListener() {
    uniffi_ant_ffi_fn_init_callback_vtable_progresslistener(UniffiCallbackInterfaceProgressListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceProgressListener {
    fileprivate static let handleMap = UniffiHandleMap<ProgressListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceProgressListener : FfiConverter {
    typealias SwiftType = ProgressListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressListener_lift(_ handle: UInt64) throws -> ProgressListener {
    return try FfiConverterCallbackInterfaceProgressListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceProgressListener_lower(_ v: ProgressListener) -> UInt64 {
    return FfiConverterCallbackInterfaceProgressListener.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypePaymentEntry: FfiConverterRustBuffer {
    typealias SwiftType = [PaymentEntry]

    public static func write(_ value: [PaymentEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePaymentEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PaymentEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [PaymentEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePaymentEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureAntFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ant_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_chunk_exists() != 23762) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_chunk_get() != 8435) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_chunk_put() != 39682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_data_get_private() != 59125) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_data_get_public() != 7309) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_data_put_private() != 63662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_data_put_public() != 34392) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_download_private_to_file() != 25712) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_download_public_to_file() != 59266) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_file_download_public() != 9845) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_file_upload_public() != 25369) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_finalize_upload() != 24158) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_finalize_upload_with_progress() != 10031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_prepare_data_upload() != 1621) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_prepare_file_upload() != 27493) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_client_wallet_approve() != 45082) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_wallet_address() != 25260) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_wallet_balance_of_gas_tokens() != 24986) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_wallet_balance_of_tokens() != 62360) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_client_connect() != 27345) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_client_connect_for_external_signer() != 7905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_client_connect_from_devnet_manifest() != 55097) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_client_connect_from_devnet_manifest_external_signer() != 58161) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_client_connect_local() != 40455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_client_connect_with_wallet() != 6225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_constructor_wallet_from_private_key() != 21803) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ant_ffi_checksum_method_progresslistener_on_progress() != 9942) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitProgressListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureAntFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all